### ISSUE TITLE
error message on pairs 

### ISSUE THREAD

**Issue by thenightisdarkandfullofterrors** [robertmartin8/CryptoGraphArb#1]
error message after downloading snapshot

Downloading snapshot...
100%|██████████| 59/59 [01:59<00:00,  2.02s/it]
Download finished. Creating adjacency matrix..
Error for BCH/ETH
Error for BCH/BNB
Error for WAVES/PAX
Error for GTO/TUSD
Error for GTO/USDC
Error for GTO/PAX
Error for BCPT/TUSD
Error for BCPT/PAX
Error for BCPT/USDC

subsequently for almost all pairs

**Comment by robertmartin8** [comment]
Has all the data correctly downloaded into the `binance_data/` folder?

**Comment by lal-r** [comment]
`Error for BCH/ETH` 
This custom error message from the **try and expect** block is printed because there is no crypto pair `BCH/ETH` in the selected exchange. This is normal because the program cross-checks the downloaded pairs with a predefined set of pairs.
